name: 'Setup Conan'
description: 'Sets up Conan for Sisl Builds'
inputs:
  platform:
    description: 'Platform conan will be building on'
    required: true
    default: 'ubuntu-24.04'
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Setup Conan and Export Recipes
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install conan~=2.0
        python -m pip install gcovr
        conan profile detect
        conan remote update conancenter --url https://center2.conan.io

    - name: Fixup libstdc++
      shell: bash
      run: |
        # Ensure std::string to non-CoW C++11 version
        sed -i 's,compiler.cppstd=.*$,compiler.cppstd=20,g' ~/.conan2/profiles/default
        sed -i 's,compiler.libcxx=libstdc++$,compiler.libcxx=libstdc++11,g' ~/.conan2/profiles/default
