name: 'Setup Conan v2'
description: 'Sets up Conan v2 for Sisl v13+ Builds'
inputs:
  platform:
    description: 'Platform conan will be building on'
    required: true
    default: 'ubuntu-24.04'
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Setup Conan and Export Recipes
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install conan~=2.0
        python -m pip install gcovr
        conan profile detect --name default

    - name: Fixup libstdc++
      shell: bash
      run: |
        # Set std::string to non-CoW C++11 version
        sed -i 's,compiler.libcxx=libstdc++$,compiler.libcxx=libstdc++11,g' ~/.conan2/profiles/default
        # Set C++ version to C++20
        sed -i 's,compiler.cppstd=.*$,compiler.cppstd=20,g' ~/.conan2/profiles/default
      if: ${{ inputs.platform == 'ubuntu-24.04' }}

