name: Sisl Build

on:
  workflow_dispatch:
  push:
    branches:
      - stable/v8.x
      - stable/v9.x
      - master

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-22.04"]
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc"]
        prerelease: ["True", "False"]
        tooling: ["Sanitize", "Coverage", "None"]
        exclude:
          - build-type: Debug
            prerelease: "False"
          - build-type: Debug
            tooling: None
          - build-type: Debug
            malloc-impl: tcmalloc
          - build-type: Release
            malloc-impl: libc
          - build-type: Release
            tooling: Sanitize
          - build-type: Release
            tooling: Coverage
    uses: ./.github/workflows/build_dependencies.yml
    with:
      platform: ${{ matrix.platform }}
      branch: ${{ github.ref }}
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}
      tooling: ${{ matrix.tooling }}
      testing: 'True'
  ChainBuild:
    runs-on: "ubuntu-22.04"
    steps:
    - name: Start IOManager Build
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CHAIN_BUILD_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/eBay/iomanager/actions/workflows/merge_build.yml/dispatches \
          -d '{"ref":"master","inputs":{}}'
      if: ${{ github.ref == 'refs/heads/master' }}
    - name: Start NuraftMesg Build
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CHAIN_BUILD_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/eBay/nuraft_mesg/actions/workflows/conan_build.yml/dispatches \
          -d '{"ref":"main","inputs":{}}'
      if: ${{ github.ref == 'refs/heads/master' }}
