name: Sisl v13 Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - stable/v13.x

jobs:
  GccThreadSanitize:
    uses: ./.github/workflows/build_dependencies.yml
    with:
      platform: "ubuntu-24.04"
      branch: ${{ github.ref }}
      build-type: "Debug"
      malloc-impl: "libc"
      sanitize: "thread"
      tooling: "None"
      testing: 'True'

  GccAddressSanitize:
    uses: ./.github/workflows/build_dependencies.yml
    with:
      platform: "ubuntu-24.04"
      branch: ${{ github.ref }}
      build-type: "Debug"
      malloc-impl: "libc"
      sanitize: "address"
      tooling: "None"
      testing: 'True'

  GccCoverage:
    uses: ./.github/workflows/build_dependencies.yml
    with:
      platform: "ubuntu-24.04"
      branch: ${{ github.ref }}
      build-type: "Debug"
      malloc-impl: "libc"
      sanitize: "False"
      tooling: "Coverage"
      testing: 'True'

  GccRelease:
    uses: ./.github/workflows/build_dependencies.yml
    with:
      platform: "ubuntu-24.04"
      branch: ${{ github.ref }}
      build-type: "Release"
      malloc-impl: "tcmalloc"
      sanitize: "False"
      tooling: "None"
      testing: 'True'
