name: Sisl v13 Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev/v13.x

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-24.04"]
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc"]
        tooling: ["Sanitize", "Coverage", "None"]
        exclude:
          - build-type: Debug
            tooling: None
          - build-type: Debug
            malloc-impl: tcmalloc
          - build-type: Release
            malloc-impl: libc
          - build-type: Release
            tooling: Sanitize
          - build-type: Release
            tooling: Coverage
    uses: ./.github/workflows/build_dependencies.yml
    with:
      platform: ${{ matrix.platform }}
      branch: ${{ github.ref }}
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      tooling: ${{ matrix.tooling }}
      testing: 'True'
