name: Check Modified File

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if file is modified
        run: |
          if git diff --unified=0 ${{ github.base_ref }}..${{ github.sha }} *conanfile.py* | grep -q "^+.*version"; then
            echo "Version is updated with this PR, OK"
          else
            echo "Conan version is not updated with this PR. Please update that to allow PR merge"
            exit 1
          fi
